### ISSUE TITLE
tcpping页面建议

### ISSUE THREAD

**Issue by lalala666plus** [reg233/nezha-theme-world-map#1]
最近的1.2更新之后，过多的tcpping服务可以翻页了，但是如果过多的话会显得麻烦，如果可以直接做成滑动就更好了

**Comment by reg233** [comment]
我尝试改成全部显示也不遮挡图标的样子

**Comment by lalala666plus** [comment]
> 我尝试改成全部显示也不遮挡图标的样子

好的辛苦

**Comment by reg233** [comment]
> > 我尝试改成全部显示也不遮挡图标的样子
> 
> 好的辛苦

不太好改，不改了，就这样吧
